version: "3"
services:
  api:
    container_name: mkad_api
    environment:
      API_ENVIRONMENT: production
      API_PORT: 5000
      YANDEX_API_KEY: d01ab74e-0df4-4ede-acef-c21d14e5c39a
      LOG_MAX_LENGTH: 20000
      LOG_LEVEL: INFO
    build:
        context: .
    ports:
      - "5000:5000"